[package]
name = "cyberbrain-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Cyberbrain: core"

[dependencies]
blake3 = "1.8.7"
ignore = "0.4.33"
jiff = { version = "0.2.35", features = ["serde"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_yaml_ng = "0.10.0"
thiserror = "2.0.20"
toml = "1.1.5"
ulid = { version = "3.0.0", features = ["serde"] }

[dev-dependencies]
tempfile = "3.27.0"
